apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-config
  namespace: distributed-wallet
data:
  SPRING_PROFILES_ACTIVE: prod

  DB_HOST: wallet-mysql-db.cuvkmcs8i5hn.us-east-1.rds.amazonaws.com
  DB_PORT: "3306"

  REDIS_HOST: wallet-redis-symft9.serverless.use1.cache.amazonaws.com
  REDIS_PORT: "6379"

  KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  ZIPKIN_URL: http://tempo:9411