apiVersion: v1
kind: Secret
metadata:
  name: wallet-secrets
  namespace: distributed-wallet
type: Opaque
data:
  # Base64 encoded 'admin'
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: d2FsbGV0MTIzNDUj
  # Base64 encoded 'admin'
  GRAFANA_PASSWORD: YWRtaW4=
