apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-wallet
  namespace: distributed-wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-wallet
  template:
    metadata:
      labels:
        app: consumer-wallet
    spec:
      containers:
      - name: consumer-wallet
        image: distributed-wallet/consumer-wallet:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-wallet
  namespace: distributed-wallet
spec:
  selector:
    app: consumer-wallet
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
